### PR TITLE
Django update

### PR DESCRIPTION
**Pull request by jturnbull**
(Redacted)

### CODE REVIEW

**Comment by mlen108** [comment]
Crocodoc API became BOX... long time ago - https://support.box.com/hc/en-us/articles/200526768-Box-Announces-the-acquisition-of-Crocodoc

**Comment by jturnbull** [comment]
@mlen108 Indeed, but they're still keeping the Crocodoc API around, as the box API [doesn't have all the features](https://trello.com/c/crloG5Dw/45-annotations-ga).

Can the Incuna account take over this repo and I'll roll a new version?

**Comment by mlen108** [comment]
This project has Apache licence so feel free to fork it (which you already did twice ;-).

**Comment by jturnbull** [comment]
Yeah, but you rejected my pull request! ;)

Can you add me as a collaborator on Pypi so I can push there?

**Comment by mlen108** [comment]
PR was rejected as this project is no longer being maintained - which is clear from the info in README...

**Comment by jturnbull** [comment]
Ah, how we've missed you.

I see the project isn't being maintained - can I take over the maintenance of the project?

**Comment by mlen108** [comment]
Indeed, fork it and have fun!

**Comment by jturnbull** [comment]
Great! Also, can you add me as a collaborator on Pypi so I can push there?

**Comment by mlen108** [comment]
`pip` can [install from git repo](https://pip.pypa.io/en/latest/reference/pip_install.html#git) as well.

**Comment by jturnbull** [comment]
That's not very community spirit though is it? If you don't want the project, let me take it over?

**Comment by mlen108** [comment]
Feel welcome to fork it and modify to your needs, also distribute it, as long as the license stays happy. It's very community friendly.

**Comment by jturnbull** [comment]
Pypi is littered with enough dead projects and their slightly-differently-named forks. Why are you being so difficult?

**Comment by mlen108** [comment]
Btw I don't think the code here is enough compatible with Django 1.7 (not to mention 1.8 version), so you might be better off with starting from scratch. It's not that difficult to write custom models fields ;-)

**Comment by jturnbull** [comment]
Thanks for the advice.

For the final time, in the interest of preventing one less dead project on Github and Pypi, can I please take over this project, that I paid you to write and that you're happy to denounce as unmaintained and abandoned?

**Comment by mlen108** [comment]
You won't save the world with one less dead project on OSS universe I'm afraid.

Anyway, I would also remind you some facts:
1) This project was majorly developed/written in my personal time (see https://github.com/mlen108/djcroco/graphs/punch-card)
2) I never worked for you.
3) Decision to happily denounce it as unmaintained did not come simple as ABC.

EOT.

**Comment by mlen108** [comment]
Thought I would stick it in here in case one wonders why I talk to myself on this PR.

j

**Pull request closed without merging**
